name: Publish Image Using Semver Tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Publish Image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Publish S3 Http Proxy Image
      uses: Ferlab-Ste-Justine/action-push-image@v2
      with:
        username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
        password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
        image: ferlabcrsj/s3-http-proxy
        tag_format: "{semver}"